version 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pipenv
      - pipenv install --system
      - cd blog
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - aws s3 sync dist/blog-kevinharper-com/blog/site/ s3://staging.blog.kevinharper.com --delete
